// hood-stock-lp: Uniswap v4 calldata builders and reads, zero-dep.
// Every encoder here is validated BYTE-FOR-BYTE against the Midpoint engine's
// viem output in selftest.mjs — the vectors were generated by the encoders
// that run the live house book. Fork quirks baked in (each cost a revert to
// find on 2026-08-09):
//   - Robinhood's UR adds a per-hop price floor `minHopPriceX36` to the
//     ExactInputSingleParams struct — omit it and the decoder slices garbage.
//     0 = no floor; amountOutMinimum is the real guard.
//   - Actions.sol values differ from upstream: TAKE_PAIR is 0x11, not 0x10.

import {
  USDG,
  HOOKS_NONE,
  POSM,
  QUOTER,
  UNIVERSAL_ROUTER,
  PERMIT2,
  STATE_VIEW,
  SEL,
  MAX_UINT160,
  MAX_UINT256,
} from "./markets.mjs";
import {
  addrWord,
  uintWord,
  intWord,
  b32Word,
  encActionsParams,
  encBytes,
  encBytesArray,
  ethCall,
  wordAt,
  toBigInt,
  toInt,
  toAddr,
  tx,
} from "./chain.mjs";

const COMMAND_V4_SWAP = "10";
const ACT = { SWAP_EXACT_IN_SINGLE: "06", SETTLE_ALL: "0c", TAKE_ALL: "0f" };
const LIQ = { MINT_POSITION: "02", BURN_POSITION: "03", SETTLE_PAIR: "0d", TAKE_PAIR: "11" };

// PoolKey for a market: currencies in canonical sort order.
export function poolKeyFor(M) {
  const [c0, c1] = M.usdgIs0 ? [USDG, M.token] : [M.token, USDG];
  return { currency0: c0, currency1: c1, fee: M.fee, tickSpacing: M.tickSpacing, hooks: HOOKS_NONE };
}

// zeroForOne: buying stock means USDG in — which is currency0 exactly when usdgIs0.
export const buyStockZeroForOne = (M) => Boolean(M.usdgIs0);
export const sellStockZeroForOne = (M) => !M.usdgIs0;

const poolKeyWords = (k) =>
  addrWord(k.currency0) +
  addrWord(k.currency1) +
  uintWord(k.fee) +
  intWord(k.tickSpacing) +
  addrWord(k.hooks);

// ---------- UniversalRouter: one exact-in swap ----------

export function swapData(poolKey, zeroForOne, amountIn, minOut, deadline) {
  const inputCurrency = zeroForOne ? poolKey.currency0 : poolKey.currency1;
  const outputCurrency = zeroForOne ? poolKey.currency1 : poolKey.currency0;
  // ExactInputSingleParams as a single dynamic tuple (hookData makes it
  // dynamic): outer offset word, 10 head words, empty-bytes tail.
  const param0 =
    uintWord(0x20) +
    poolKeyWords(poolKey) +
    uintWord(zeroForOne ? 1 : 0) +
    uintWord(amountIn) +
    uintWord(minOut) +
    uintWord(0) + // minHopPriceX36 — the fork's extra field; 0 = no floor
    uintWord(0x140) + // hookData offset within the tuple (10 words)
    uintWord(0); // hookData length
  const param1 = addrWord(inputCurrency) + uintWord(amountIn); // SETTLE_ALL
  const param2 = addrWord(outputCurrency) + uintWord(minOut); // TAKE_ALL
  const input = encActionsParams(
    ACT.SWAP_EXACT_IN_SINGLE + ACT.SETTLE_ALL + ACT.TAKE_ALL,
    [param0, param1, param2]
  );
  // execute(bytes commands, bytes[] inputs, uint256 deadline)
  const commands = encBytes(COMMAND_V4_SWAP);
  return (
    SEL.urExecute +
    uintWord(0x60) +
    uintWord(0x60 + commands.length / 2) +
    uintWord(deadline) +
    commands +
    encBytesArray([input])
  );
}

// ---------- POSM modifyLiquidities: mint / burn ----------

export function mintData(poolKey, tickLower, tickUpper, liquidity, amount0Max, amount1Max, owner, deadline) {
  const param0 =
    poolKeyWords(poolKey) +
    intWord(tickLower) +
    intWord(tickUpper) +
    uintWord(liquidity) +
    uintWord(amount0Max) +
    uintWord(amount1Max) +
    addrWord(owner) +
    uintWord(0x180) + // hookData offset (12 head words)
    uintWord(0);
  const param1 = addrWord(poolKey.currency0) + addrWord(poolKey.currency1); // SETTLE_PAIR
  const unlockData = encActionsParams(LIQ.MINT_POSITION + LIQ.SETTLE_PAIR, [param0, param1]);
  return SEL.modifyLiquidities + uintWord(0x40) + uintWord(deadline) + encBytes(unlockData);
}

// Burn a position completely (auto-decreases to zero, fees included) and
// take both sides to `recipient` — principal + fees land in one tx.
export function burnData(poolKey, tokenId, recipient, deadline) {
  const param0 =
    uintWord(tokenId) + uintWord(0) + uintWord(0) + uintWord(0x80) + uintWord(0);
  const param1 =
    addrWord(poolKey.currency0) + addrWord(poolKey.currency1) + addrWord(recipient); // TAKE_PAIR
  const unlockData = encActionsParams(LIQ.BURN_POSITION + LIQ.TAKE_PAIR, [param0, param1]);
  return SEL.modifyLiquidities + uintWord(0x40) + uintWord(deadline) + encBytes(unlockData);
}

// ---------- Quoter: simulate a swap through the real pool ----------

export function quoterData(poolKey, zeroForOne, amountIn) {
  return (
    SEL.quoteExactInputSingle +
    uintWord(0x20) +
    poolKeyWords(poolKey) +
    uintWord(zeroForOne ? 1 : 0) +
    uintWord(amountIn) +
    uintWord(0x100) + // hookData offset (8 head words)
    uintWord(0)
  );
}

export async function quoteSwap(poolKey, zeroForOne, amountIn) {
  const out = await ethCall(QUOTER, quoterData(poolKey, zeroForOne, amountIn));
  return { amountOut: toBigInt(wordAt(out, 0)), gasEstimate: toBigInt(wordAt(out, 1)) };
}

// ---------- Permit2 approvals ----------
// Token pulls in v4 go through Permit2, two-step: ERC20 approve to Permit2
// once (MAX — pool math rounds up a wei; exact allowances revert), then a
// Permit2 allowance for the actual spender (router or POSM).

export function permit2ApproveData(token, spender, expiration) {
  return (
    SEL.permit2Approve +
    addrWord(token) +
    addrWord(spender) +
    uintWord(MAX_UINT160) +
    uintWord(expiration)
  );
}

// The unsigned approval txs a wallet needs before `spender` may pull `token`
// via Permit2 — reads current allowances, returns [] if both already stand.
export async function approvalTxs(owner, token, neededRaw, spender, label) {
  const now = Math.floor(Date.now() / 1000);
  const txs = [];
  const erc20Allow = toBigInt(
    wordAt(await ethCall(token, SEL.allowance + addrWord(owner) + addrWord(PERMIT2)), 0)
  );
  if (erc20Allow < neededRaw) {
    txs.push(
      tx(token, SEL.approve + addrWord(PERMIT2) + uintWord(MAX_UINT256), `approve ${label} -> Permit2 (max, one-time)`)
    );
  }
  const p2 = await ethCall(
    PERMIT2,
    SEL.permit2Allowance + addrWord(owner) + addrWord(token) + addrWord(spender)
  );
  const p2Amount = toBigInt(wordAt(p2, 0));
  const p2Exp = Number(toBigInt(wordAt(p2, 1)));
  if (p2Amount < neededRaw || p2Exp < now + 600) {
    txs.push(
      tx(PERMIT2, permit2ApproveData(token, spender, now + 30 * 86400), `Permit2 allowance ${label} (30 days)`)
    );
  }
  return txs;
}

// ---------- reads ----------

export async function v4PoolState(poolId, usdgIs0) {
  const slot = await ethCall(STATE_VIEW, SEL.getSlot0 + b32Word(poolId));
  const liq = await ethCall(STATE_VIEW, SEL.getLiquidity + b32Word(poolId));
  const sqrtPriceX96 = toBigInt(wordAt(slot, 0));
  const tick = Number(toInt(wordAt(slot, 1)));
  const sqrtP = Number(sqrtPriceX96) / 2 ** 96;
  const raw = sqrtP * sqrtP;
  return {
    sqrtPriceX96,
    tick,
    sqrtP,
    liquidity: toBigInt(wordAt(liq, 0)),
    price: usdgIs0 ? 1e12 / raw : raw * 1e12,
  };
}

// PositionInfo is packed: bits 8..31 tickLower, 32..55 tickUpper (int24s).
export function unpackTicks(infoBigInt) {
  const s24 = (v) => (v >= 1n << 23n ? Number(v - (1n << 24n)) : Number(v));
  return {
    tickLower: s24((infoBigInt >> 8n) & 0xffffffn),
    tickUpper: s24((infoBigInt >> 32n) & 0xffffffn),
  };
}

export function decodePoolAndPositionInfo(dataNo0x) {
  return {
    currency0: toAddr(wordAt(dataNo0x, 0)),
    currency1: toAddr(wordAt(dataNo0x, 1)),
    fee: Number(toBigInt(wordAt(dataNo0x, 2))),
    tickSpacing: Number(toInt(wordAt(dataNo0x, 3))),
    hooks: toAddr(wordAt(dataNo0x, 4)),
    ...unpackTicks(toBigInt(wordAt(dataNo0x, 5))),
  };
}

// Owed fees: growth inside the range since the position's last snapshot.
// v4 has no tokensOwed store — the delta IS the uncollected balance.
const Q128 = 1n << 128n;
const M256 = (1n << 256n) - 1n;

export async function v4OwedFees(poolId, tokenId, tickLower, tickUpper) {
  const salt = uintWord(tokenId);
  const posInfo = await ethCall(
    STATE_VIEW,
    SEL.getPositionInfo + b32Word(poolId) + addrWord(POSM) + intWord(tickLower) + intWord(tickUpper) + salt
  );
  const L = toBigInt(wordAt(posInfo, 0));
  const last0 = toBigInt(wordAt(posInfo, 1));
  const last1 = toBigInt(wordAt(posInfo, 2));
  const inside = await ethCall(
    STATE_VIEW,
    SEL.getFeeGrowthInside + b32Word(poolId) + intWord(tickLower) + intWord(tickUpper)
  );
  const in0 = toBigInt(wordAt(inside, 0));
  const in1 = toBigInt(wordAt(inside, 1));
  return {
    owed0Raw: Number((((in0 - last0) & M256) * L) / Q128),
    owed1Raw: Number((((in1 - last1) & M256) * L) / Q128),
  };
}
